### PR TITLE
HangmanGame w/ 2 New methods

### PR DESCRIPTION
**Pull request by originalGitHubName**

### CODE REVIEW

**Review by kahan002 — COMMENTED** [review]
These set and get newGame, but newGame was not added as a member variable. I am also feeling that perhaps sine the new game request comes from the GUI, it should reside there.

**Review by kahan002 — COMMENTED** [review]
also, by naming the file hangmanGame as opposed to HangmanGame, you're not getting changes committed. Rather, it's adding another file to the project that defines the same class. That will get unpredictable quickly.

**Comment by originalGitHubName** [comment]
Ok, so to sum up, I should move the two methods over to HangmanGui, close the pull requests so its not so confusing, and rename the files properly?

**Comment by kahan002** [comment]
I just created a pull request with your changes, changed a little.There was something subtle going on with the code not giving itself time to updtae the Gui. I changed the newGame from a boolean to a JLabel, and I added Thread.sleep to the main loop.It's a bit fussy, still, but the functionality seems there.jak

    On Sunday, June 14, 2020, 10:28:08 AM CDT, originalGitHubName <notifications@github.com> wrote:  
 
 


Ok, so to sum up, I should move the two methods over to HangmanGui, close the pull requests so its not so confusing, and rename the files properly?

**Comment by kahan002** [comment]
ideas incorporated into master

**Pull request closed without merging**
